// ============================================
// MORPHEUS BUILDER — File Packaging & Download
// 
// Takes the files generated by the agent and
// packages them into a real, runnable project.
// Generates package.json, vite config, index.html,
// and bundles everything into a downloadable zip.
// ============================================

import JSZip from 'jszip'
import { saveAs } from 'file-saver'

/**
 * Generate a complete project scaffold around the agent's files
 * Returns an object with ALL files needed for a runnable project
 */
export function scaffoldProject(agentFiles, designSystem = {}) {
  const project = {}

  // ---- package.json ----
  project['package.json'] = JSON.stringify({
    name: 'morpheus-generated-app',
    private: true,
    version: '1.0.0',
    description: 'Generated by Morpheus — AI-powered interface builder',
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'vite build',
      preview: 'vite preview'
    },
    dependencies: {
      'react': '^18.2.0',
      'react-dom': '^18.2.0',
      'lucide-react': '^0.344.0'
    },
    devDependencies: {
      '@types/react': '^18.2.56',
      '@types/react-dom': '^18.2.19',
      '@vitejs/plugin-react': '^4.2.1',
      'autoprefixer': '^10.4.17',
      'postcss': '^8.4.35',
      'tailwindcss': '^3.4.1',
      'vite': '^5.1.4'
    }
  }, null, 2)

  // ---- vite.config.js ----
  project['vite.config.js'] = `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})`

  // ---- tailwind.config.js ----
  const primaryColor = designSystem.primary_color || '#7c3aed'
  const secondaryColor = designSystem.secondary_color || '#6366f1'

  project['tailwind.config.js'] = `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '${primaryColor}',
        secondary: '${secondaryColor}',
      },
      fontFamily: {
        sans: ['${designSystem.font_family || 'Inter'}, system-ui, sans-serif'],
      },
    },
  },
  plugins: [],
}`

  // ---- postcss.config.js ----
  project['postcss.config.js'] = `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`

  // ---- index.html ----
  const fontFamily = designSystem.font_family || 'Inter'
  const fontUrl = getFontUrl(fontFamily)

  project['index.html'] = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Morpheus</title>
    ${fontUrl ? `<link href="${fontUrl}" rel="stylesheet" />` : ''}
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>`

  // ---- src/main.jsx ----
  project['src/main.jsx'] = `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)`

  // ---- src/index.css ----
  project['src/index.css'] = `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  padding: 0;
  font-family: '${fontFamily}', system-ui, sans-serif;
  background: ${designSystem.background_color || '#ffffff'};
  color: ${designSystem.text_color || '#1a1a1a'};
}`

  // ---- Agent-generated files go into src/ ----
  for (const [filename, fileData] of Object.entries(agentFiles)) {
    const code = typeof fileData === 'string' ? fileData : fileData.code
    // Ensure files are in src/ directory
    const path = filename.startsWith('src/') ? filename : `src/${filename}`
    project[path] = code
  }

  // ---- README.md ----
  const fileList = Object.keys(agentFiles).map(f => `  - ${f}`).join('\n')
  project['README.md'] = `# Generated by Morpheus
> AI-powered interface builder — built on Hermes by Nous Research

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

## Files Generated
${fileList}

## Tech Stack
- React 18
- Tailwind CSS
- Vite
- Lucide React (icons)

---
*Built autonomously by [Morpheus](https://github.com) powered by Hermes*`

  return project
}

/**
 * Generate a Google Fonts URL for common font families
 */
function getFontUrl(fontFamily) {
  const fontMap = {
    'Inter': 'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap',
    'Roboto': 'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap',
    'Open Sans': 'https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap',
    'Poppins': 'https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap',
    'Montserrat': 'https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&display=swap',
    'Lato': 'https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap',
    'Nunito': 'https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;500;600;700;800;900&display=swap',
    'Playfair Display': 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700;800;900&display=swap',
    'Source Sans Pro': 'https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@300;400;500;600;700;800;900&display=swap',
    'DM Sans': 'https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600;700&display=swap',
    'Space Grotesk': 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap',
  }

  // Try exact match first
  if (fontMap[fontFamily]) return fontMap[fontFamily]

  // Try case-insensitive match
  const lower = fontFamily.toLowerCase()
  for (const [name, url] of Object.entries(fontMap)) {
    if (name.toLowerCase() === lower) return url
  }

  // Try to construct a generic Google Fonts URL
  const formatted = fontFamily.replace(/\s+/g, '+')
  return `https://fonts.googleapis.com/css2?family=${formatted}:wght@300;400;500;600;700;800&display=swap`
}

/**
 * Package all project files into a zip and trigger download
 */
export async function downloadProject(agentFiles, designSystem = {}, projectName = 'morpheus-app') {
  const zip = new JSZip()
  const project = scaffoldProject(agentFiles, designSystem)

  // Add every file to the zip
  for (const [filepath, content] of Object.entries(project)) {
    zip.file(filepath, content)
  }

  // Generate zip blob
  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 }
  })

  // Trigger download
  const safeName = projectName.replace(/[^a-zA-Z0-9-_]/g, '-').toLowerCase()
  saveAs(blob, `${safeName}.zip`)

  return {
    fileCount: Object.keys(project).length,
    size: blob.size
  }
}

/**
 * Generate files object formatted for Sandpack live preview
 * Sandpack needs a specific format: { '/App.jsx': code, ... }
 */
export function formatForSandpack(agentFiles, designSystem = {}) {
  const sandpackFiles = {}

  // Core index.css with Tailwind imports
  const fontFamily = designSystem.font_family || 'Inter'
  sandpackFiles['/index.css'] = {
    code: `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  padding: 0;
  font-family: '${fontFamily}', system-ui, sans-serif;
  background: ${designSystem.background_color || '#ffffff'};
  color: ${designSystem.text_color || '#1a1a1a'};
}

/* Smooth scrolling */
html { scroll-behavior: smooth; }

/* Better defaults */
img { max-width: 100%; height: auto; }
* { box-sizing: border-box; }`,
    active: false
  }

  // Add agent-generated files
  for (const [filename, fileData] of Object.entries(agentFiles)) {
    const code = typeof fileData === 'string' ? fileData : fileData.code
    // Sandpack wants paths starting with /
    const cleanName = filename.replace(/^src\//, '').replace(/^\//, '')
    const sandpackPath = `/${cleanName}`
    
    sandpackFiles[sandpackPath] = {
      code,
      active: cleanName === 'App.jsx'
    }
  }

  // Ensure App.jsx exists — if the agent named it differently, create a wrapper
  if (!sandpackFiles['/App.jsx']) {
    // Look for any file that might be the main app
    const appFile = Object.keys(sandpackFiles).find(f => 
      f.toLowerCase().includes('app') && f.endsWith('.jsx')
    )
    
    if (appFile) {
      // Rename it
      sandpackFiles['/App.jsx'] = sandpackFiles[appFile]
      delete sandpackFiles[appFile]
    } else {
      // Create a minimal App that imports the first component
      const firstComponent = Object.keys(sandpackFiles).find(f => 
        f.endsWith('.jsx') && f !== '/App.jsx'
      )
      
      if (firstComponent) {
        const componentName = firstComponent.replace('/', '').replace('.jsx', '')
        sandpackFiles['/App.jsx'] = {
          code: `import ${componentName} from './${componentName}'\n\nexport default function App() {\n  return <${componentName} />\n}`,
          active: true
        }
      }
    }
  }

  return sandpackFiles
}

/**
 * Get file extension icon/emoji for the file list UI
 */
export function getFileIcon(filename) {
  const ext = filename.split('.').pop()?.toLowerCase()
  const icons = {
    'jsx': '⚛️',
    'js': '📜',
    'tsx': '⚛️',
    'ts': '📜',
    'css': '🎨',
    'html': '🌐',
    'json': '📦',
    'md': '📝',
    'svg': '🖼️',
    'png': '🖼️',
    'jpg': '🖼️',
  }
  return icons[ext] || '📄'
}

/**
 * Estimate project complexity from file count and total lines
 */
export function estimateComplexity(files) {
  const fileCount = Object.keys(files).length
  let totalLines = 0

  for (const fileData of Object.values(files)) {
    const code = typeof fileData === 'string' ? fileData : fileData.code
    totalLines += (code?.split('\n').length || 0)
  }

  if (totalLines > 500 || fileCount > 10) return { level: 'complex', label: 'Complex', color: '#f87171' }
  if (totalLines > 200 || fileCount > 5) return { level: 'moderate', label: 'Moderate', color: '#fbbf24' }
  return { level: 'simple', label: 'Simple', color: '#34d399' }
}
